apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"initContainers":[{"name":"wait-for-kafka"}],"containers":[{"limits":{"cpu":"1","memory":"2Gi"},"requests":{"cpu":"500m","memory":"1Gi"},"name":"ml-consumer"}]},"output":{"initContainers":[{"limits":{"ephemeral-storage":"1Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"1Gi"},"name":"wait-for-kafka"}],"containers":[{"limits":{"cpu":"1","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"1Gi"},"name":"ml-consumer"}]},"computeClassAtAdmission":"Default","modified":true}'
    autopilot.gke.io/warden-version: 33.33.19-gke.1
    deployment.kubernetes.io/revision: "13"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ml-consumer"},"name":"ml-consumer","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ml-consumer"}},"template":{"metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"9090","prometheus.io/scrape":"true"},"labels":{"app":"ml-consumer"}},"spec":{"containers":[{"env":[{"name":"KAFKA_BOOTSTRAP_SERVERS","value":"kafka:9092"},{"name":"METRICS_PORT","value":"9090"},{"name":"PYTHONUNBUFFERED","value":"1"}],"image":"us-central1-docker.pkg.dev/gen-lang-client-0282248851/ai-platform/ml-consumer:latest","lifecycle":{"preStop":{"exec":{"command":["/bin/sh","-c","sleep 10"]}}},"livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":9090},"initialDelaySeconds":60,"periodSeconds":30,"timeoutSeconds":10},"name":"ml-consumer","ports":[{"containerPort":9090,"name":"metrics","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":9090},"initialDelaySeconds":30,"periodSeconds":10,"timeoutSeconds":5},"resources":{"limits":{"cpu":"1000m","memory":"2Gi"},"requests":{"cpu":"500m","memory":"1Gi"}}}],"initContainers":[{"args":["echo \"Waiting for Kafka to be ready...\"\nuntil nc -z kafka 9092; do\n  echo \"Kafka not ready, waiting...\"\n  sleep 2\ndone\necho \"Kafka is ready!\"\n"],"command":["sh","-c"],"image":"busybox:1.35","name":"wait-for-kafka"}]}}}}
  creationTimestamp: "2025-10-18T18:00:47Z"
  generation: 15
  labels:
    app: ml-consumer
  name: ml-consumer
  namespace: default
  resourceVersion: "1761332376410719015"
  uid: 12cda09b-1541-4126-b513-438d7eca6cd9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ml-consumer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-10-24T14:58:59-04:00"
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: ml-consumer
    spec:
      containers:
      - env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: METRICS_PORT
          value: "9090"
        - name: PYTHONUNBUFFERED
          value: "1"
        image: us-central1-docker.pkg.dev/gen-lang-client-0282248851/ai-platform/ml-consumer:latest
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 10
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: ml-consumer
        ports:
        - containerPort: 9090
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 1Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - |
          echo "Waiting for Kafka to be ready..."
          until nc -z kafka 9092; do
            echo "Kafka not ready, waiting..."
            sleep 2
          done
          echo "Kafka is ready!"
        command:
        - sh
        - -c
        image: busybox:1.35
        imagePullPolicy: IfNotPresent
        name: wait-for-kafka
        resources:
          limits:
            ephemeral-storage: 1Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 1Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-10-24T18:59:36Z"
    lastUpdateTime: "2025-10-24T18:59:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-10-18T18:00:47Z"
    lastUpdateTime: "2025-10-24T18:59:36Z"
    message: ReplicaSet "ml-consumer-7444c6d6c6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
