# ============================================================================
# Organization - Teams and Users
# ============================================================================

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform engineering team
spec:
  type: team
  profile:
    displayName: Platform Team
    email: platform@example.com
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: data-team
  description: Data engineering team
spec:
  type: team
  profile:
    displayName: Data Team
    email: data@example.com
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
  memberOf: [platform-team]
